const srLatinLocale = {
  code: "sr-Latn",
  week: {
    dow: 1,
    doy: 7,
  },
  buttonText: {
    prev: "Preth.",
    next: "Sledeći",
    today: "Danas",
    month: "Mesec",
    week: "Nedelja",
    day: "Dan",
    list: "Planer",
  },
  weekText: "Sed",
  allDayText: "Ceo dan",
  moreLinkText: function (n) {
    return "+ još " + n;
  },
  noEventsText: "Nema događaja za prikaz",

  // Dodato — latinica
  dayNames: [
    "Nedelja",
    "Ponedeljak",
    "Utorak",
    "Sreda",
    "Četvrtak",
    "Petak",
    "Subota",
  ],
  dayNamesShort: ["Ned", "Pon", "Uto", "Sre", "Čet", "Pet", "Sub"],
  monthNames: [
    "Januar",
    "Februar",
    "Mart",
    "April",
    "Maj",
    "Jun",
    "Jul",
    "Avgust",
    "Septembar",
    "Oktobar",
    "Novembar",
    "Decembar",
  ],
  monthNamesShort: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "Maj",
    "Jun",
    "Jul",
    "Avg",
    "Sep",
    "Okt",
    "Nov",
    "Dec",
  ],
};
